steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=heroku/buildpacks:18', '--path', 'samples/python', '--publish', 'gcr.io/ccpa-394520/cloudbowl-samples-python:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '--image=gcr.io/ccpa-394520/cloudbowl-samples-python:$COMMIT_SHA', '--platform=managed', '--project=ccpa-394520', '--region=us-west1', '--allow-unauthenticated', '--memory=256Mi', 'cloudbowl-samples-python']

# options:
#   logging: CLOUD_LOGGING_ONLY